// angular-learning/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { SidebarComponent } from "../app/Components/sidebar/sidebar.component";
import { NavbarComponent } from "../app/Components/navbar/navbar.component";
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, SidebarComponent, NavbarComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'angular-learning';
}

<div class="antialiased bg-gray-50 dark:bg-gray-900">
<app-navbar/>

  <!-- Sidebar -->

<app-sidebar/>

  <main class="p-4 md:ml-64 h-screen pt-20">
    <router-outlet></router-outlet>
  </main>
</div>

// vue-learning/src/App.vue

<script setup lang="ts">
import navbar from './components/navbar.vue';
import sidebar from './components/sidebar.vue';
</script>
<template>
  <div class="antialiased bg-gray-50 dark:bg-gray-900">

    <navbar />

    <!-- Sidebar -->
    <sidebar />


    <main class="p-4 md:ml-64 h-screen pt-20">
      <RouterView />
    </main>
  </div>
</template>

<style scoped></style>
